### ISSUE TITLE
Adequately document RA controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#270] opened 2016-08-31 22:53 UTC
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [Google Doc for RA](https://docs.google.com/document/d/1x0aCxMO05-ujEc3KR5J37UJMsxFXPdpAL3eGNqiejlQ/edit)

**Acceptance criteria**

RA overall: 
- [x] RA-1 is updated to reflect 18F/GSA's actual policies. (This depends on https://github.com/18F/cg-compliance/issues/179)
- [x] We've read through RA overall to identify any obvious incorrect or incomplete statements, control originations, or implementation statuses.
- [x] We've fixed any obvious incorrect or incomplete statements, control originations, or implementation statuses. This includes converting sentences from passive voice to active voice when helpful to clarify statements.
- [x] RA control statements link to any relevant docs.cloud.gov pages that have more detail.
- [x] We've asked our ISSO to check whether RA includes adequate procedural documentation.

**Implementation guidance**

During grooming, take items from the following and list them as specific tasks above.

- [x] [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit))
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "moderate" differential (if not already marked green there).
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "low" differential (if not already marked done there).
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our ISSO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our PMO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Any relevant notes in the [SSP check working space](https://docs.google.com/document/d/1k-qiOF66o4ssBr6kEO_akaGNsku2zt2jrcawZGg7ZsA/edit#)
- [x] Check that control origination statements make sense (look for [notes here](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940) and look through the controls); if you change a checkbox, make a note in that spreadsheet.

**Comment by cnelson** [comment] 2016-09-12 16:05
This is blocked until https://github.com/18F/cg-compliance/issues/179 is closed.  Once our policies are confirmed to be correct, we can begin documenting/implementing the procedures that enforce them.

**Comment by NoahKunin** [comment] 2016-09-13 02:27
Doing this final mapping tonight, having @brittag look at it first thing Pacific time tmrw, then will :shipit: to unblock.

**Comment by brittag** [comment] 2016-09-14 06:45
I added a few questions about minor aspects of control statements. If this is basically waiting for ISSO review, we could probably move it to "Awaiting Acceptance" instead of "In Progress". :D

**Comment by brittag** [comment] 2016-09-15 01:26
I've asked Bridget to take a look at these.

**Comment by mogul** [comment] 2016-09-15 19:38
Bridget said it looks pretty good, but she's made some suggestions. Sounds like she's done with it for now.

**Comment by mogul** [comment] 2016-09-16 22:50
Per discussion with Noah today: @rjbator will be the one to sign off on this issue and move it from `Awaiting Acceptance` to `Closed`.

**Comment by rjbator** [comment] 2016-09-17 20:30
I made a pass on the RA and a few comments.  I see Bridget still has some comments that have not been marked "resolved" yet but looks like they have been addressed.  Are we expecting to wait for Bridget to make another pass or should we mark these resolved?

**Comment by brittag** [comment] 2016-09-20 19:00
Remaining problems I see blocking this from moving to closed, as flagged in the doc:

* We need info about whether a few things should be "OCISO" or "OCIO".
* We need info about GSA IT scans.

@rjbator can you take another look at the questions from Chris in that doc and see if you have info to help answer them? Thank you!

(Fixing the -1 statement doesn't need to block this since it's filed separately at https://github.com/18F/cg-product/issues/306.)

**Comment by rjbator** [comment] 2016-09-20 19:23
I will circle back and look at them.

**Comment by NoahKunin** [comment] 2016-09-26 03:16
Taking this over so we meet the deadline.

**Comment by NoahKunin** [comment] 2016-10-13 23:53
This was done!

**Closed by NoahKunin** 2016-10-13 23:53 UTC
Labels: HighBar
