### ISSUE TITLE
Document how to set up non-sandbox orgs

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#82] opened 2016-07-15 18:45 UTC

**Comment by afeld** [comment] 2016-11-23 20:33
Per https://gsa-tts.slack.com/archives/cloud-gov-skyporter/p1479933001004170:

1. [Org request form](https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSd4HmcGfJW3EBnpewTFDD-urRFPp1LN0DcwNB_FxZgUn8ho9g/viewform?c=0&w=1) filled out by 18F staff.
1. @berndverst confirms information is correct in [the response spreadsheet](https://docs.google.com/spreadsheets/d/1Bdzl9n2E1MXWV4elXvZ-nYuZmmEj4PEU-u5aZlNGZF4/edit#gid=131031416).
1. @berndverst files ticket in Zendesk for current Atlas on call and assigns to that person.
1. Atlas support on call creates the org.

**Comment by berndverst** [comment] 2016-11-23 20:41
Dupe of https://github.com/18F/cg-site/issues/219 ?

**Comment by afeld** [comment] 2016-11-23 20:44
Well, appears that it is documented at https://cloud.gov/docs/ops/create-org/#non-sandboxes, but that maybe we need to add the steps listed above. So maybe this issue can be converted to "elaborate on org request/creation procedure"?

**Closed** 2017-03-22 03:48 UTC
Labels: business
