### ISSUE TITLE
Rotate credentials using [CredHub|Vault]

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#944] opened 2019-07-07 23:52 UTC
As operators we want [CredHub|Vault] to be able to regenerate any internal usernames and passwords so we don't have to generate and rotate those credentials by hand.

## Acceptance Criteria
- [ ] We can successfully rotate credentials using [CredHub|Vault]

**Comment by bengerman13** [comment] 2019-11-14 20:51
@mxplusb can this be closed as a duplicate of your other CH work?

**Comment by mxplusb** [comment] 2019-11-15 13:24
I'm doing the necessary requirements to make this a reality, so I would say this is the acceptance criteria for the other work I'm doing.

**Comment by mxplusb** [comment] 2020-01-16 20:43
Okay, I think Credhub won, so closing this since a decision has been reached and we've successfully rotated credentials multiple times.

**Closed** 2020-01-16 20:44 UTC
Labels: operations
