### ISSUE TITLE
Outage free logsearch updates

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#673] opened 2017-01-21 00:45 UTC
In order to eliminate outages in our logs service, we want to support rolling restarts after logsearch updates without triggering recovery conditions

**Acceptance criteria**

- [x] Replicate production volume characteristics to facilitate investigations for this and future improvements without disturbing production
- [ ] The cluster stays yellow / green during a stemcell update, and smoke tests pass immediately afterwards
- [ ] Alerts are not generated for the cluster being in a yellow state while a deployment is in process

**Comment by cnelson** [comment] 2017-01-27 21:53
### Nodes run out of file descriptors and stop responding
- [We should make this hardcoded limit configurable](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/elasticsearch/templates/bin/elasticsearch_ctl#L50) and set it to at least 128k
- The release should run ES with `-Des.max-open-files=true` so that it logs the ulimit on startup.

### The rolling restart may be taking down multiple nodes at the same time
[Monit is only looking for a pid file](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/elasticsearch/monit#L2) to determine if ES has started but this file is written almost immediately after the JVM starts, but it could be several minutes before ES has actually rejoined the cluster and is really "running". 

- We should put in a `post-start` script that waits for ES to rejoin the cluster.  [UAA does something similar since it takes so long to really start](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/post-start).
  - This script should be smart enough to:
    - Wait for the node to rejoin the cluster and halt the deploy if it does not in a given time
    - Re-enable allocation when run on data nodes
    - Possibly increase recovery settings to a large number `'{"transient":{"cluster.routing.allocation.node_concurrent_recoveries":"128", "indices.recovery.concurrent_streams": "256", "indices.store.throttle.type": "none"}}'` 
    - Monitor cluster health until state is green and shard allocation is complete
    - Return recovery settings to normal

 ### The cluster does not wait long enough for nodes to rejoin
`index.unassigned.node_left.delayed_timeout` defaults to `1m` in ES which is not enough time for a data node to update and rejoin the cluster.  [This causes all primary shards on a data node to fail over to their replicas (which then triggers new replicas to be created)](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/delayed-allocation.html) whenever an update is performed.

- We should set `index.unassigned.node_left.delayed_timeout` on all indices to something large enough to cover a stemcell update.


cc: @jmcarp @rogeruiz

**Comment by cnelson** [comment] 2017-02-01 01:43
### Upstreamis unstable
Upstream frequently commits breaking changes without notice.  This has happened twice in the last two weeks: https://github.com/18F/cg-deploy-logsearch/pull/51, https://github.com/18F/cg-deploy-logsearch/pull/46
- @jmcarp has issues upstream about getting stable releases from them https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/issues/195, https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/issues/225

**Comment by jmcarp** [comment] 2017-02-13 23:27
For a better health check, I was testing the following on staging:

```
check host elasticsearch with address localhost
  start program "/var/vcap/jobs/elasticsearch/bin/monit_debugger elasticsearch_ctl '/var/vcap/jobs/elasticsearch/bin/elasticsearc
h_ctl start'" with timeout 120 seconds
  stop program "/var/vcap/jobs/elasticsearch/bin/monit_debugger elasticsearch_ctl '/var/vcap/jobs/elasticsearch/bin/elasticsearch
_ctl stop'"
  if failed url http://localhost:9200/_cluster/health
    timeout 15 seconds
    for 5 cycles
  then restart
  group vcap
```

Which works as expected. WDYT about sending a patch upstream with that logic, substituting templated variables for constants? We can also include a spec variable that allows for the current monit behavior in case folks don't want to change to http health checks.

**Comment by cnelson** [comment] 2017-02-14 15:02
LGTM but will this cause a deployment to fail with it using `then restart`?  If not, WDYT about using `then stop`? 

The goal would be to make sure that if a node fails to come back up during a rolling update that we fail the deployment and then an operator can fix it while it's only one node and then kick off a new deployment

**Comment by jmcarp** [comment] 2017-02-15 04:56
I've been running into issues trying to get the monit health check to work in real life:
* If we configure monit to stop the task after e.g. 3 consecutive failures, monit thinks the task is in a healthy state until the third failure: initializing -> healthy -> unhealthy.
* When we use `check host` instead of `check process`, running `monit restart` seems to trigger the stop and start calls so close together that the start doesn't take effect.

So I'm thinking we should go with @cnelson 's original plan of waiting for each node to join the cluster in `post-start`. I'd also be happy to pair on this and see if the monit http check is viable after all--it's very possible that I'm missing something obvious here.

**Comment by jmcarp** [comment] 2017-02-17 15:40
Let's agree on criteria for outage-free updates. How about: the cluster stays yellow / green during a stemcell update, and smoke tests pass immediately afterwards?

**Comment by cnelson** [comment] 2017-02-17 18:23
I also think as part of this effort we need to `stable` the `Service elasticsearch health is in state warning on host...` riemann alerts to match up with our acceptable time for cluster in the yellow stage, so we don't get a bunch of open issues every time we do a rolling restart.

**Comment by jmcarp** [comment] 2017-02-21 16:51
We sent a handful of pull requests upstream to resolve issues that [@cnelson - Chris Nelson] identified:

[merged] https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/34
[reviewing] https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/38
[reviewing] https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/39

We also made a few changes to our own repos:
[merged] https://github.com/18F/cg-riemann-boshrelease/pull/69
[blocked] https://github.com/18F/cg-deploy-logsearch/pull/53

Once these are in good shape and merged, we'll run another stemcell update and verify the ACs.

**Comment by rogeruiz** [comment] 2017-03-03 18:24
Upstream merged our PR, there's a config change left to do and then  we'll redeploy on staging.

**Comment by cnelson** [comment] 2017-03-07 21:11
Confirmed during maint window that deploy works as expected.

Rolled out monitoring updates here: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-monitoring/jobs/deploy-monitoring-production/builds/162

We may need future tuning of timeouts as we gather more data, but that should be handled as white-noise-support-work so I'm calling this done.

**Closed** 2017-03-08 07:42 UTC
Labels: Atlas
