### ISSUE TITLE
Make a list of fixes for cloud.gov IdP UX

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-product#538] opened 2016-12-02 15:44 UTC
We need better error messaging & form validation to provide better services to our IdP users on par with other parts of the platform. 

This will be touching a few different applications.

- Shibboleth [cloud.gov IdP](https://github.com/18F/shibboleth-boshrelease)
- UAA [cg-uaa](https://github.com/18F/cg-uaa)
- Accounts [cg-uaa-extras](https://github.com/18F/cg-uaa-extras)

Acceptance criteria:
- [x] Screencast walking through current state is available in Google Drive: https://drive.google.com/drive/folders/0B_a71ksF1BfnMVRGTEV2dUxHbjg
- [x] A list of recommended fixes are in a Github issue

**Comment by rogeruiz** [comment] 2016-12-02 15:44
We're going to groom this later today at 3pm with the Navigator team.

cc: @suprenant

**Comment by rogeruiz** [comment] 2016-12-02 21:07
Should this try to cover as well 18F/cg-product#496?

**Comment by brittag** [comment] 2016-12-02 21:07
Notes from Atlas/Navigator discussion today: https://docs.google.com/document/d/1XCK1qbd0d15oIvSFyPAmlDBYToxZZyDOo6UH5aziK_k/edit

**Comment by suprenant** [comment] 2016-12-05 16:45
Bret and I discussed this a bit further after the meeting last week. Even if our migration plan is shifting, we do want to still do some user-testing around the invitation-and-provisioning process so that we have a shared understanding of how stable/usable it is for mass-migration purposes. 

That said, we don't want to dedicate a huge amount of time beyond that to fixing things found which might throw off other work, though if we can provide some lift and possibly clean up some minor/cosmetic fixes, that would be good.

cc @thisisdano @vz3 @line47

**Comment by rogeruiz** [comment] 2016-12-05 19:07
I'm uploaded the screencast to Google Drive ✌️

**Comment by mogul** [comment] 2016-12-07 17:51
Removed `Atlas` label as the rest of this one falls on `Navigator`

**Comment by suprenant** [comment] 2016-12-07 18:21
@rogeruiz can we still expect those additional requested screencasts from you? If we could get one for Change Password and also Forgot Password, that would be helpful.

**Comment by rogeruiz** [comment] 2016-12-19 17:48
Finishing up these videos today. Had to redeploy staging-shibboleth metadata.

**Comment by suprenant** [comment] 2016-12-20 19:09
Super, thanks @rogeruiz! 

FYI @vz3 @thisisdano

**Comment by suprenant** [comment] 2016-12-27 18:37
Talking about this now in grooming. Thinking we could use some content help and could use @vz3 to lead this so we can see some progress in this sprint or next.

**Comment by vz3** [comment] 2017-01-06 08:39
Starting notes here.

![screen shot 2017-01-05 at 3 25 39 pm](https://cloud.githubusercontent.com/assets/582918/21711494/4fe201e4-d3bd-11e6-92e0-f16b399b011b.png)
Can we place this message on the actual login page?

![screen shot 2017-01-05 at 3 25 45 pm](https://cloud.githubusercontent.com/assets/582918/21711497/4fe2cc82-d3bd-11e6-8fd9-f119c5fa591a.png)
- Remove bottom section including login, create account link (assuming it doesn't work), and reset password.
- Change top copy to something like:
    > Select your sign in method.

![screen shot 2017-01-05 at 3 25 55 pm](https://cloud.githubusercontent.com/assets/582918/21711749/92a13f1c-d3be-11e6-948d-9e695b370017.png)
- Link "Forgot your password?" to `/reset-password` page.
- `Need help` doesn't seem to do anything. Remove or link to email or GitHub.
- Clear prior granting… language unclear. Try something like "I no longer want my information release to Cloud.gov" if this is needed, but it seems like something that _really_ should not go here. Consider moving to account view.

![screen shot 2017-01-05 at 3 54 23 pm](https://cloud.githubusercontent.com/assets/582918/21711495/4fe20824-d3bd-11e6-890e-bb53a9c9ded9.png)
- Change header to: "Forgot your password"
- Consider adding additional copy here with the instructions that are in the email.
    > Submitting your password here will reset your password. After you have logged back in, you can change your password.
- Change "Send email" to "Send temporary password"

![screen shot 2017-01-05 at 3 55 52 pm](https://cloud.githubusercontent.com/assets/582918/21711496/4fe248e8-d3bd-11e6-8150-08007b38d5eb.png)
- Good

![screen shot 2017-01-05 at 5 26 50 pm](https://cloud.githubusercontent.com/assets/582918/21711499/4fe6fd8e-d3bd-11e6-9e73-35222593dba3.png)
- Try something like (though @brittag should def weigh in on this one):
*Subject line*
> Your cloud.gov password has been reset

*Body*
> We have received a request to reset your cloud.gov password. If you did not send this request, please disregard this message.
To reset your password:
1) Verify your email address here and we will send you a temporary password.
2) Log in with your temporary password, and you will be prompted to change your password.

_Please note that step 2's copy does not match up to how the process currently works._ Please address that.

![screen shot 2017-01-05 at 5 29 32 pm](https://cloud.githubusercontent.com/assets/582918/21711498/4fe34da6-d3bd-11e6-94a8-0a4f402d97ff.png)
- Entering an invalid email results in a non-descriptive `Internal Server Error`
![screen shot 2017-01-05 at 5 29 34 pm](https://cloud.githubusercontent.com/assets/582918/21711500/4fea90e8-d3bd-11e6-8c89-4d477b4f0626.png)
- Entering an invalid email results in a non-descriptive `Internal Server Error`

![screen shot 2017-01-06 at 2 37 02 am](https://cloud.githubusercontent.com/assets/582918/21711502/4feae372-d3bd-11e6-8bfd-2768c5587c98.png)
- Header: `Request a temporary password.`

![screen shot 2017-01-06 at 2 37 12 am](https://cloud.githubusercontent.com/assets/582918/21711504/4feb3304-d3bd-11e6-9ded-2956da0fb6bd.png)
- Header: `Here is your temporary password.`
Perhaps include copy button. When I tried double clicking, additional whitespace appeared after the password. Could this be fixed by placing the password in an HTML form field or something?

![screen shot 2017-01-06 at 2 37 32 am](https://cloud.githubusercontent.com/assets/582918/21711503/4feae3ae-d3bd-11e6-9f3a-d94af3fab946.png)
- Same note as before. Can this be incoporated into the next screen?

![screen shot 2017-01-06 at 2 37 39 am](https://cloud.githubusercontent.com/assets/582918/21711501/4feadb48-d3bd-11e6-9f3c-75a2cab45bd6.png)
- Same notes as before.

![screen shot 2017-01-06 at 2 37 46 am](https://cloud.githubusercontent.com/assets/582918/21711505/4ff29950-d3bd-11e6-9329-4df5fa4463fe.png)
- Same notes as before.

![screen shot 2017-01-06 at 2 38 32 am](https://cloud.githubusercontent.com/assets/582918/21711510/4ff403c6-d3bd-11e6-989b-e5be817254bc.png)
- Invalid token doesn't result in an error. Please provide feedback.
- Consider more instructions here.
    > When you created your account, you associated it with a multi-factor authorization code generator like Authy or Google Authenticator. Please open the application and enter the token code.

![screen shot 2017-01-06 at 2 38 47 am](https://cloud.githubusercontent.com/assets/582918/21711509/4ff3e206-d3bd-11e6-8142-566f0ee87f63.png)
- Same notes as before

![screen shot 2017-01-06 at 2 38 52 am](https://cloud.githubusercontent.com/assets/582918/21711507/4ff3ce7e-d3bd-11e6-8cdd-cb85fa896369.png)
- Consider sending straight to dashboard and adding 'invite users' and 'account settings' functionality to dashboard. Unless…

![screen shot 2017-01-06 at 2 39 45 am](https://cloud.githubusercontent.com/assets/582918/21711511/4ffaf4f6-d3bd-11e6-8536-a10467041edf.png)
- This is all the info that's in account settings? The 'profile' stuff is not useful _unless_ we add a password reset button here, which I believe is expected behavior. Otherwise a hashtag pw is useless.

![screen shot 2017-01-06 at 2 41 22 am](https://cloud.githubusercontent.com/assets/582918/21711513/4ffbbc92-d3bd-11e6-8e84-7d42f2c319e8.png)
- Let's hyperlink this where the "reset password" links are.

![screen shot 2017-01-06 at 2 42 20 am](https://cloud.githubusercontent.com/assets/582918/21711514/4ffca30a-d3bd-11e6-8c5b-bcd628b0631a.png)
- Real time password validation would be very nice.

![screen shot 2017-01-06 at 2 42 50 am](https://cloud.githubusercontent.com/assets/582918/21711515/4ffcdafa-d3bd-11e6-877b-2adea801bb75.png)
- Fine

![screen shot 2017-01-06 at 2 42 56 am](https://cloud.githubusercontent.com/assets/582918/21711517/500239be-d3bd-11e6-8b6a-d5d9c5d0db65.png)
- Fine but link back to account page would be nice.

**Comment by suprenant** [comment] 2017-01-06 16:33
@vz3 nice! Is there any other feedback you feel would be helpful (@mogul @thisisdano) before we close this one up and file away the work?

**Comment by mogul** [comment] 2017-01-06 16:36
Thanks! Unfortunately we can't make the warning part of the following view due to compliance requirements.

The content changes all make sense. Any recommendations on swapping out images and styling @thisisdano ?

**Comment by adborden** [comment] 2017-01-13 01:27
There's a placeholder for this work in PI9

**Closed by adborden** 2017-01-13 01:27 UTC
Labels: Navigator

**Comment by adborden** [comment] 2017-01-13 01:28
https://app.mural.ly/t/gsa6/m/gsa6/1483852699525
