### ISSUE TITLE
Migrate Logsearch to Credhub

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1110] opened 2019-10-09 18:08 UTC
Migrate Logsearch to Credhub

In order to get Logsearch credentials into Credhub, we need to import Logsearch's variables into Credhub.

## Acceptance Criteria

- [ ] Development Logsearch manifest should be identical to existing manifest, but with variables pulled from Credhub.
- [ ] Staging Logsearch manifest should be identical to existing manifest, but with variables pulled from Credhub.
- [ ] Production Logsearch manifest should be identical to existing manifest, but with variables pulled from Credhub.

**Comment by karareinsel** [comment] 2019-10-09 18:59
Provided @bengerman13 finishes his log search work #961 then it makes sense to tackle this in the next sprint (19.10.30).

**Comment by mxplusb** [comment] 2019-12-18 17:49
This still needs to get done - that being said I'm not sure if it would be a higher priority than Kubernetes, though (i.e. which should come first).

**Comment by karareinsel** [comment] 2019-12-18 18:16
I would say that it's not a higher priority than the K8s work nor the Coalfire artifacts list.

**Comment by mxplusb** [comment] 2019-12-19 17:13
Sure, but this and Coalfire's priorities are separate - I was musing about this work's priority in reference to the greater Credhub work, not comparing against other priorities.

**Comment by bengerman13** [comment] 2020-01-06 19:22
duplicate of #1111

**Closed by bengerman13** 2020-01-06 19:22 UTC
Labels: operations
