### ISSUE TITLE
Close POAM V16-AC-10: Concurrent Sessions

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#446] opened 2016-10-28 00:49 UTC
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Acceptance Criteria**

After AC-10 mitigation is implemented (https://github.com/18F/cg-product/issues/559):

- [ ] We've written a draft revision of the AC-10 control statement in the [future SSP edits doc](https://docs.google.com/document/d/1CWi8efCQKi6TS5oxm76YpSvx3pyQMiW-F0i7lIsdBXk/edit).
- [ ] We've updated our [ConMon POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) with information about this, including relatively detailed notes in the comments column.

**More Information**
- See [ConMon POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.
- [NIST Special Publication 800-53 (Rev. 4) AC-10](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-10)

**Comment by cnelson** [comment] 2016-10-28 03:04
This one is about UAA and going to need some discussion, and perhaps remediation

**Comment by brittag** [comment] 2016-11-05 01:26
Updated story with a couple more implementation sketch details (left vague to accommodate discussion).

**Comment by NoahKunin** [comment] 2016-12-12 19:35
See Google Doc for comment, re-posting here: since we can't block, please start alert on more than 3 (negotiable) concurrent sessions per use w/in first 90 days.

**Comment by brittag** [comment] 2016-12-12 23:33
Updated this story to reflect our new plan for this item; accompanying technical work is in a story at https://github.com/18F/cg-product/issues/559

**Comment by mogul** [comment] 2016-12-22 01:21
We're hoping to at least be able to point to #559 as groomed by December 30th.

**Comment by brittag** [comment] 2017-02-04 03:34
Updated story with my revised understanding of how to complete POAM items post-P-ATO.

**Comment by brittag** [comment] 2017-03-01 02:36
This is pretty much a duplicate of https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-935 since that card has the Deviation Request Form task, so I'll move this to "done" instead of keeping it in blocked.

**Closed** 2017-03-01 02:36 UTC
Labels: blocked, HighBar, POAM

**Comment by brittag** [comment] 2017-03-03 19:27
We can move this to Done after any/all followup tasks are captured on the Highbar & Atlas boards.

**Comment by rogeruiz** [comment] 2017-03-07 22:47
Related Atlas card in PI9 Task List https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-935
